import Header from '@/components/layout/Header';
import Footer from '@/components/layout/Footer';
import DomainInputForm from '@/components/forms/DomainInputForm';
import Image from 'next/image';

export default function HomePage() {
    return (
        <div className="min-h-screen flex flex-col">
            <Header />

            <main className="flex-1 flex flex-col items-center justify-center px-6 py-20">
                {/* Background Effects */}
                <div className="fixed inset-0 pointer-events-none overflow-hidden">
                    <div className="absolute top-1/4 left-1/4 w-[500px] h-[500px] rounded-full bg-electric/5 blur-[120px]" />
                    <div className="absolute bottom-1/4 right-1/4 w-[400px] h-[400px] rounded-full bg-electric/3 blur-[100px]" />
                </div>

                {/* Hero */}
                <div className="relative z-10 w-full max-w-4xl mx-auto text-center mb-12 animate-fade-in">
                    {/* Logo */}
                    <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-electric/10 border border-electric/20 mb-8">
                        <Image
                            src="https://growthmarketingstudios.com/wp-content/uploads/2025/11/Growth-Marketing-Studios-logo.png"
                            alt="Growth Marketing Studios"
                            width={24}
                            height={24}
                            className="rounded"
                        />
                        <span className="text-sm text-electric-400 font-medium">Growth Marketing Studios</span>
                    </div>

                    <h1 className="text-5xl md:text-7xl font-extrabold text-white mb-6 leading-tight">
                        Complete SEO Analysis
                        <br />
                        <span className="gradient-text">in Seconds</span>
                    </h1>

                    <p className="text-lg md:text-xl text-slate-400 max-w-2xl mx-auto mb-12 leading-relaxed">
                        Enter up to 5 domains to get a full technical SEO audit powered by DataForSEO and AI.
                    </p>

                    {/* Domain Input */}
                    <DomainInputForm />
                </div>

                {/* Features Grid */}
                <div className="relative z-10 w-full max-w-5xl mx-auto mt-24 grid grid-cols-1 md:grid-cols-3 gap-6 animate-slide-up">
                    {[
                        {
                            icon: '📊',
                            title: '12 Data Modules',
                            desc: 'Comprehensive analysis covering SERP, keywords, backlinks, on-page, content, and more.',
                        },
                        {
                            icon: '🤖',
                            title: 'AI-Powered Reports',
                            desc: 'Get actionable recommendations generated by GPT-4o with prioritized action plans.',
                        },
                        {
                            icon: '📄',
                            title: 'PDF Export',
                            desc: 'Download branded Executive Summary and Full Technical Audit reports.',
                        },
                    ].map((feature) => (
                        <div key={feature.title} className="glass-card p-6 text-center group">
                            <div className="w-14 h-14 mx-auto mb-4 rounded-2xl bg-electric/10 border border-electric/20 flex items-center justify-center text-2xl group-hover:scale-110 transition-transform">
                                {feature.icon}
                            </div>
                            <h3 className="text-lg font-bold text-white mb-2">{feature.title}</h3>
                            <p className="text-sm text-slate-400 leading-relaxed">{feature.desc}</p>
                        </div>
                    ))}
                </div>
            </main>

            <Footer />
        </div>
    );
}
